"""The optimised THC fit (Result 78), and the gradient everything rests on.

The comparison against Result 77 is only meaningful if the optimiser is actually
minimising the objective the experiment documents. A first derivation of the
gradient was wrong on both blocks -- a spurious factor of two and an unwarranted
symmetrisation of the coupling gradient -- and L-BFGS would have happily
converged on something else. So the gradient check is the load-bearing test here,
not the scaling result.
"""

from __future__ import annotations

import numpy as np
import pytest

from experiments.exp022_optimised_thc import _objective, optimised_thc_fit, thc_tensor


def _pack(chi, coupling):
    return np.concatenate([chi.ravel(), coupling.ravel()])


def test_analytic_gradient_matches_finite_differences():
    """Checked on both blocks, on a target that carries the model's symmetries.

    A first version tested against a target symmetrised the wrong way and could
    not tell a correct gradient from an incorrect one -- both looked wrong. The
    target here is generated *by* the model, so any disagreement is the
    gradient's.
    """
    rng = np.random.default_rng(0)
    orbitals, rank = 4, 6

    truth_chi = rng.normal(size=(orbitals, rank)) * 0.5
    truth_coupling = rng.normal(size=(rank, rank))
    truth_coupling = 0.5 * (truth_coupling + truth_coupling.T)
    target = thc_tensor(truth_chi, truth_coupling)

    chi = rng.normal(size=(orbitals, rank)) * 0.5
    coupling = rng.normal(size=(rank, rank))
    coupling = 0.5 * (coupling + coupling.T)
    packed = _pack(chi, coupling)

    _, gradient = _objective(packed, orbitals, rank, target)

    epsilon = 1e-6
    worst = 0.0
    for index in range(len(packed)):
        step = np.zeros_like(packed)
        step[index] = epsilon
        high, _ = _objective(packed + step, orbitals, rank, target)
        low, _ = _objective(packed - step, orbitals, rank, target)
        numeric = (high - low) / (2 * epsilon)
        worst = max(worst, abs(numeric - gradient[index]) / max(abs(numeric), 1e-9))

    assert worst < 1e-4, f"gradient disagrees with finite differences by {worst:.2e}"


def test_the_objective_is_zero_on_an_exact_model():
    """Sanity: a target generated by the model must be fitted exactly."""
    rng = np.random.default_rng(3)
    orbitals, rank = 3, 5
    chi = rng.normal(size=(orbitals, rank))
    coupling = rng.normal(size=(rank, rank))
    coupling = 0.5 * (coupling + coupling.T)
    target = thc_tensor(chi, coupling)

    value, gradient = _objective(_pack(chi, coupling), orbitals, rank, target)
    assert value == pytest.approx(0.0, abs=1e-20)
    assert np.max(np.abs(gradient)) == pytest.approx(0.0, abs=1e-10)


def test_the_reconstruction_carries_the_required_symmetries():
    """Chemists' 8-fold symmetry, or qiskit-nature rejects the tensor outright.

    Result 77 lost this at the 1e-16 level and the sweep crashed before the ranks
    where THC starts working.
    """
    rng = np.random.default_rng(1)
    chi = rng.normal(size=(4, 6))
    coupling = rng.normal(size=(6, 6))
    coupling = 0.5 * (coupling + coupling.T)
    tensor = thc_tensor(chi, coupling)

    np.testing.assert_allclose(tensor, tensor.transpose(1, 0, 2, 3), atol=1e-12)
    np.testing.assert_allclose(tensor, tensor.transpose(0, 1, 3, 2), atol=1e-12)
    np.testing.assert_allclose(tensor, tensor.transpose(2, 3, 0, 1), atol=1e-12)


def test_the_one_norm_absorbs_the_column_norms():
    """chi is not unit-norm after optimisation, unlike the selected version.

    Result 77's chi came from `eigh` and was normalised, so its 1-norm was Z's
    alone. Here chi is free, and a coupling entry means nothing without the
    |chi|^2 factors on each side. Omitting them would understate lambda -- in the
    direction that flatters this experiment against Result 77.
    """
    from qres.factorization import molecular_integrals
    from qres.problems.chemistry import build_molecule

    problem = build_molecule("H2")
    one_body, two_body, _ = molecular_integrals(problem)
    fit = optimised_thc_fit(one_body, two_body, rank=4, iterations=200)

    chi, coupling = fit["chi"], fit["coupling"]
    scale = np.linalg.norm(chi, axis=0) ** 2
    expected = float(0.5 * np.abs(coupling * np.outer(scale, scale)).sum())
    naive = float(0.5 * np.abs(coupling).sum())

    assert fit["one_norm"] == pytest.approx(expected, rel=1e-12)
    # and the correction is not cosmetic on a real fit
    assert not np.isclose(expected, naive, rtol=1e-6) or np.allclose(scale, 1.0)


def test_a_single_start_is_not_reproducible_and_multi_start_is():
    """The failure that forced multi-start, pinned so it cannot be forgotten.

    With all three guards in place, H4 at M=12 gave 3.4e-8 on one run and 9.3e-3
    on the next -- five orders of magnitude, both converged. The landscape has
    multiple local minima and floating-point noise picks between them.

    This test does not re-run that race; it pins the *evidence* of it, which the
    experiment now records: the spread of residuals across restarts. A spread of
    one would mean restarts are pointless and the whole mechanism could go.
    """
    import json
    from pathlib import Path

    path = Path("results/exp022_optimised_thc.json")
    if not path.exists():
        pytest.skip("run experiments.exp022_optimised_thc first")

    data = json.loads(path.read_text())
    spreads = [
        entry["restart_residual_spread"]
        for row in data["rows"]
        for entry in row["sweep"]
        if "restart_residual_spread" in entry
    ]
    assert spreads, "the experiment must record restart spreads"
    assert max(spreads) > 10.0, (
        "restarts now all reach the same optimum; if that is real the multi-start "
        "machinery is unnecessary, and this test should be replaced rather than relaxed"
    )


def test_multi_start_never_does_worse_than_its_own_first_start():
    """Taking the best of several starts must be monotone in the number of starts.

    A bug in the selection (picking by the wrong key, say) would show up as the
    six-start fit being worse than the one-start fit it contains.
    """
    from qres.factorization import molecular_integrals
    from qres.problems.chemistry import build_molecule

    from experiments.exp022_optimised_thc import optimised_thc_fit

    problem = build_molecule("H4")
    one_body, two_body, _ = molecular_integrals(problem)

    single = optimised_thc_fit(one_body, two_body, rank=12, iterations=4000, restarts=1)
    several = optimised_thc_fit(one_body, two_body, rank=12, iterations=4000, restarts=4)

    assert several["residual"] <= single["residual"] * (1 + 1e-9), (
        f"four starts ({several['residual']:.3e}) did worse than one "
        f"({single['residual']:.3e})"
    )
