"""Correctness of the quantum-kernel comparison and its classical baselines.

The failure mode here is a flattering comparison rather than a wrong number: a
classical baseline given one badly-chosen kernel, or a dataset that happens to
suit the quantum feature map without saying so.  Result 67 turns on both being
handled explicitly, so both are tested.

The `ad_hoc` dataset is *deliberately* matched to the quantum kernel -- labels
are generated by measuring the feature-mapped state.  That is the point, and the
test below pins it: if it ever stops being circular, the conclusion drawn from
it has to be re-derived.
"""

from __future__ import annotations

import numpy as np
import pytest

from qres.problems.learning import (
    ad_hoc_dataset,
    best_classical_accuracy,
    kernel_ridge_classify,
    linear_dataset,
    linear_kernel,
    moons_dataset,
    polynomial_kernel,
    quantum_kernel_accuracy,
    quantum_kernel_matrix,
    rbf_kernel,
)


def test_train_and_test_sets_are_disjoint():
    """A leaked test point makes every accuracy here meaningless."""
    for build in (linear_dataset, moons_dataset, ad_hoc_dataset):
        dataset = build(seed=0)
        train = {tuple(np.round(row, 12)) for row in dataset.train_x}
        test = {tuple(np.round(row, 12)) for row in dataset.test_x}
        assert not (train & test), f"{dataset.name}: overlapping split"
        assert len(dataset.train_x) == len(dataset.train_y)
        assert len(dataset.test_x) == len(dataset.test_y)


def test_labels_are_two_class_and_roughly_balanced():
    for build in (linear_dataset, moons_dataset, ad_hoc_dataset):
        dataset = build(samples=120, seed=1)
        for labels in (dataset.train_y, dataset.test_y):
            assert set(np.unique(labels)) <= {-1.0, 1.0}
        balance = float(np.mean(dataset.train_y > 0))
        assert 0.2 < balance < 0.8, f"{dataset.name}: labels {balance:.2f} positive"


def test_kernel_ridge_separates_a_trivially_separable_problem():
    """If the classifier cannot do this, no comparison built on it means anything."""
    dataset = linear_dataset(samples=200, seed=0)
    train_kernel = linear_kernel(dataset.train_x, dataset.train_x)
    test_kernel = linear_kernel(dataset.test_x, dataset.train_x)
    predicted = kernel_ridge_classify(train_kernel, dataset.train_y, test_kernel)
    assert float(np.mean(predicted == dataset.test_y)) > 0.9


@pytest.mark.parametrize(
    "kernel", [linear_kernel, rbf_kernel(0.5), polynomial_kernel(3)]
)
def test_classical_kernels_are_symmetric_and_psd(kernel):
    """A non-PSD kernel makes the ridge solve meaningless, silently."""
    dataset = moons_dataset(samples=60, seed=0)
    matrix = kernel(dataset.train_x, dataset.train_x)
    assert np.allclose(matrix, matrix.T, atol=1e-10)
    eigenvalues = np.linalg.eigvalsh(matrix)
    assert eigenvalues.min() > -1e-8, f"smallest eigenvalue {eigenvalues.min():.2e}"


def test_quantum_kernel_is_symmetric_with_unit_diagonal():
    """A fidelity kernel: |<phi(x)|phi(x)>|^2 is exactly 1."""
    dataset = moons_dataset(samples=30, seed=0)
    matrix, _ = quantum_kernel_matrix(dataset.train_x, dataset.train_x)
    assert np.allclose(np.diag(matrix), 1.0, atol=1e-10)
    assert np.allclose(matrix, matrix.T, atol=1e-10)
    assert matrix.min() >= -1e-12 and matrix.max() <= 1 + 1e-12


def test_the_classical_baseline_searches_a_grid():
    """A baseline tuned worse than the quantum side is not a baseline.

    Checked by construction: the reported best must be at least as good as any
    single kernel chosen in advance.
    """
    dataset = moons_dataset(samples=120, seed=0)
    best = best_classical_accuracy(dataset)

    for kernel in (linear_kernel, rbf_kernel(0.5), polynomial_kernel(2)):
        train_kernel = kernel(dataset.train_x, dataset.train_x)
        test_kernel = kernel(dataset.test_x, dataset.train_x)
        predicted = kernel_ridge_classify(train_kernel, dataset.train_y, test_kernel)
        single = float(np.mean(predicted == dataset.test_y))
        assert best["accuracy"] >= single - 1e-12


def test_ad_hoc_is_circular_by_construction_and_the_others_are_not():
    """The load-bearing fact behind Result 67.

    On data generated by the feature map the quantum kernel is near-perfect; on
    ordinary data it is at or below what a linear kernel achieves.  If that ever
    inverts, the conclusion changes.
    """
    matched = quantum_kernel_accuracy(ad_hoc_dataset(samples=100, seed=0))
    assert matched["accuracy"] > 0.9, "the kernel should excel on its own data"

    ordinary = quantum_kernel_accuracy(linear_dataset(samples=100, seed=0))
    classical = best_classical_accuracy(linear_dataset(samples=100, seed=0))
    assert ordinary["accuracy"] < classical["accuracy"], (
        "the quantum kernel should lose on data it did not generate"
    )


def test_quantum_kernel_circuits_are_shallow_enough_to_survive_noise():
    """Why QML is the only class here that passes the encoding-cost criterion.

    Six two-qubit gates per kernel entry on two features, and the noisy accuracy
    matches the exact one -- unlike every other problem class in this project.
    """
    from qres.noise import make_environment

    dataset = ad_hoc_dataset(samples=24, seed=0)
    environment = make_environment("heron", seed=0)

    noisy, gates = quantum_kernel_matrix(
        dataset.train_x, dataset.train_x, environment=environment
    )
    assert 0 < gates <= 20, f"expected a shallow kernel circuit, got {gates} gates"

    exact, _ = quantum_kernel_matrix(dataset.train_x, dataset.train_x)
    assert np.abs(noisy - exact).mean() < 0.15, "noise should barely move this kernel"
