"""Quantum kernels, and the classical baselines they have to beat.

Quantum machine learning was named in the task and this project dismissed it by
argument -- "the classical baseline is too strong" -- without measuring it.  That
is exactly the move Results 42, 50 and 64 each punished: three times, a problem
looked hard until the reference was built properly, and twice the quantum
machinery had already been written by then.

So the same three criteria apply as to chemistry, MaxCut and folding
(RESEARCH_LOG Result 61):

* **required relative accuracy** -- classification tolerates percent-level error,
  so this passes trivially, which is what makes QML superficially attractive
* **classical baseline** -- the question, and the one being dodged by argument
* **encoding cost** -- gates per kernel entry against the measured budget

The datasets matter more than the model here.  A quantum kernel is a similarity
measure induced by a feature map, so on data *generated by that feature map* it
is guaranteed to do well and the comparison is circular.  ``ad_hoc`` is exactly
that construction (Havlicek et al.), included precisely so the circularity is
measured rather than hidden: it is the dataset the field's central positive
result uses.

Classical baselines are kernel ridge classifiers -- exact, closed form, no
optimiser to misconfigure, and no sklearn dependency.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any, Callable

import numpy as np


@dataclass
class Dataset:
    name: str
    train_x: np.ndarray
    train_y: np.ndarray
    test_x: np.ndarray
    test_y: np.ndarray
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def features(self) -> int:
        return self.train_x.shape[1]


def _split(x, y, train_fraction: float, rng) -> Dataset:
    order = rng.permutation(len(x))
    x, y = x[order], y[order]
    cut = int(len(x) * train_fraction)
    return x[:cut], y[:cut], x[cut:], y[cut:]


def linear_dataset(samples: int = 120, features: int = 2, seed: int = 0) -> Dataset:
    """Two Gaussian blobs -- a control that everything must solve."""
    rng = np.random.default_rng(seed)
    half = samples // 2
    x = np.vstack([
        rng.normal(+1.0, 0.8, size=(half, features)),
        rng.normal(-1.0, 0.8, size=(samples - half, features)),
    ])
    y = np.concatenate([np.ones(half), -np.ones(samples - half)])
    return Dataset("linear", *_split(x, y, 0.7, rng))


def moons_dataset(samples: int = 120, noise: float = 0.2, seed: int = 0) -> Dataset:
    """Two interleaving crescents -- linearly inseparable, trivial for RBF."""
    rng = np.random.default_rng(seed)
    half = samples // 2
    theta_a = rng.uniform(0, np.pi, half)
    theta_b = rng.uniform(0, np.pi, samples - half)
    upper = np.column_stack([np.cos(theta_a), np.sin(theta_a)])
    lower = np.column_stack([1 - np.cos(theta_b), 0.5 - np.sin(theta_b)])
    x = np.vstack([upper, lower]) + rng.normal(0, noise, size=(samples, 2))
    y = np.concatenate([np.ones(half), -np.ones(samples - half)])
    return Dataset("moons", *_split(x, y, 0.7, rng))


def ad_hoc_dataset(samples: int = 100, features: int = 2, gap: float = 0.3, seed: int = 0) -> Dataset:
    """Labels generated *by* the quantum feature map (Havlicek et al.).

    A random diagonal observable is measured on the feature-mapped state, and
    the label is its sign.  The quantum kernel is therefore matched to the data
    by construction -- which is the point: this is the dataset behind the
    field's central positive result, and measuring how a quantum kernel does
    here says something different from measuring it on data that arose from
    anything else.
    """
    from qiskit.circuit.library import ZZFeatureMap
    from qiskit.quantum_info import Statevector

    rng = np.random.default_rng(seed)
    feature_map = ZZFeatureMap(feature_dimension=features, reps=2)

    dimension = 1 << features
    diagonal = rng.choice([-1.0, 1.0], size=dimension)

    # Sample first, then threshold at the MEDIAN.  Splitting at zero instead
    # produced 94% of one class on two of three seeds and 10% on the third --
    # a dataset where a constant classifier scores 0.94, which makes any
    # accuracy comparison on it nearly meaningless.  A random +-1 diagonal has
    # no reason to have zero expectation over feature-mapped states, and the
    # original construction centres the observable for exactly this reason.
    pool = rng.uniform(0, 2 * np.pi, size=(6 * samples, features))
    values = np.array([
        float(np.sum(np.abs(Statevector(feature_map.assign_parameters(point)).data) ** 2 * diagonal))
        for point in pool
    ])
    threshold = float(np.median(values))
    spread = float(np.std(values)) or 1.0

    keep = np.abs(values - threshold) >= gap * spread  # drop the ambiguous band
    pool, values = pool[keep], values[keep]
    order = rng.permutation(len(pool))[:samples]

    points = pool[order].tolist()
    labels = [1.0 if values[i] > threshold else -1.0 for i in order]

    x = np.array(points)
    y = np.array(labels)
    dataset = Dataset("ad_hoc", *_split(x, y, 0.7, rng))
    dataset.metadata["balance"] = float(np.mean(y > 0))
    return dataset


# --------------------------------------------------------------------------
# classical kernels and an exact classifier
# --------------------------------------------------------------------------

def linear_kernel(a, b):
    return a @ b.T


def rbf_kernel(gamma: float) -> Callable:
    def kernel(a, b):
        squared = (
            np.sum(a**2, axis=1)[:, None] + np.sum(b**2, axis=1)[None, :] - 2 * a @ b.T
        )
        return np.exp(-gamma * np.maximum(squared, 0.0))
    return kernel


def polynomial_kernel(degree: int) -> Callable:
    def kernel(a, b):
        return (1.0 + a @ b.T) ** degree
    return kernel


def kernel_ridge_classify(train_kernel, train_y, test_kernel, ridge: float = 1e-3):
    """Closed-form kernel ridge, thresholded at zero.

    Exact -- no optimiser, no learning rate, nothing to misconfigure.  A weak
    baseline here would make the quantum side look better for free, which is the
    failure this whole project keeps finding.
    """
    n = len(train_y)
    weights = np.linalg.solve(train_kernel + ridge * np.eye(n), train_y)
    return np.sign(test_kernel @ weights)


def best_classical_accuracy(dataset: Dataset, ridges=(1e-4, 1e-3, 1e-2, 1e-1)) -> dict:
    """Best test accuracy over a grid of classical kernels and ridges.

    Given the grid rather than a single setting, because a classical baseline
    tuned worse than the quantum one is not a baseline.
    """
    started = time.perf_counter()
    candidates: list[tuple[str, Callable]] = [("linear", linear_kernel)]
    candidates += [(f"rbf/{g:g}", rbf_kernel(g)) for g in (0.05, 0.1, 0.5, 1.0, 2.0, 5.0)]
    candidates += [(f"poly/{d}", polynomial_kernel(d)) for d in (2, 3, 4)]

    best = {"accuracy": 0.0, "kernel": None}
    for name, kernel in candidates:
        train_kernel = kernel(dataset.train_x, dataset.train_x)
        test_kernel = kernel(dataset.test_x, dataset.train_x)
        for ridge in ridges:
            predicted = kernel_ridge_classify(train_kernel, dataset.train_y, test_kernel, ridge)
            accuracy = float(np.mean(predicted == dataset.test_y))
            if accuracy > best["accuracy"]:
                best = {"accuracy": accuracy, "kernel": f"{name} ridge={ridge:g}"}

    best["seconds"] = time.perf_counter() - started
    return best


# --------------------------------------------------------------------------
# the quantum kernel
# --------------------------------------------------------------------------

def quantum_kernel_matrix(a: np.ndarray, b: np.ndarray, reps: int = 2, environment=None):
    """Fidelity kernel ``|<phi(x)|phi(y)>|^2`` from a ZZ feature map.

    Exact by statevector when ``environment`` is ``None``.  Under a device the
    standard estimator is the compute-uncompute circuit -- prepare ``phi(x)``,
    apply ``phi(y)^dagger``, measure the all-zeros probability -- whose gate
    count is what the budget has to accommodate, and it is returned alongside.
    """
    from qiskit.circuit.library import ZZFeatureMap
    from qiskit.quantum_info import Statevector

    features = a.shape[1]
    feature_map = ZZFeatureMap(feature_dimension=features, reps=reps)

    if environment is None:
        states_a = [Statevector(feature_map.assign_parameters(x)).data for x in a]
        states_b = [Statevector(feature_map.assign_parameters(y)).data for y in b]
        matrix = np.empty((len(a), len(b)))
        for i, sa in enumerate(states_a):
            for j, sb in enumerate(states_b):
                matrix[i, j] = abs(np.vdot(sa, sb)) ** 2
        return matrix, 0

    # Transpile ONCE.  The compute-uncompute circuit has the same structure for
    # every kernel entry -- only the parameters differ -- so transpiling inside
    # the loop repeats identical work 1 120 times on a 40-sample dataset.  This
    # is the pattern `ShotEstimator` already uses for the same reason.
    from qiskit.circuit import ParameterVector

    left = ParameterVector("l", features)
    right = ParameterVector("r", features)
    template = feature_map.assign_parameters(list(left)).compose(
        feature_map.assign_parameters(list(right)).inverse()
    )
    template.measure_all()
    isa = environment.prepare(template, optimization_level=1)
    gates = sum(
        n for gate, n in isa.count_ops().items()
        if gate in {"cx", "cz", "ecr", "cy", "swap", "rzz"}
    )

    zeros = "0" * features
    matrix = np.empty((len(a), len(b)))
    circuits, index = [], []
    for i, x in enumerate(a):
        for j, y in enumerate(b):
            circuits.append(isa.assign_parameters(np.concatenate([x, y])))
            index.append((i, j))

    # and run them in batches rather than one call per entry
    batch = 256
    for start in range(0, len(circuits), batch):
        chunk = circuits[start : start + batch]
        results = environment.run(chunk, 2048)
        if not isinstance(results, list):
            results = [results]
        for (i, j), counts in zip(index[start : start + batch], results):
            matrix[i, j] = counts.get(zeros, 0) / sum(counts.values())

    return matrix, gates


def quantum_kernel_accuracy(dataset: Dataset, reps: int = 2, environment=None,
                            ridges=(1e-4, 1e-3, 1e-2, 1e-1)) -> dict:
    """Best test accuracy from the quantum kernel, same ridge grid as classical."""
    started = time.perf_counter()
    train_kernel, gates = quantum_kernel_matrix(
        dataset.train_x, dataset.train_x, reps, environment
    )
    test_kernel, _ = quantum_kernel_matrix(
        dataset.test_x, dataset.train_x, reps, environment
    )

    best = 0.0
    for ridge in ridges:
        predicted = kernel_ridge_classify(train_kernel, dataset.train_y, test_kernel, ridge)
        best = max(best, float(np.mean(predicted == dataset.test_y)))

    return {
        "accuracy": best,
        "two_qubit_gates_per_entry": gates,
        "kernel_entries": len(dataset.train_x) ** 2 + len(dataset.test_x) * len(dataset.train_x),
        "seconds": time.perf_counter() - started,
    }
